# Generated by Django 5.0.12 on 2025-04-29 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vlog",
            name="video",
            field=models.FileField(blank=True, null=True, upload_to="vlogs/videos/"),
        ),
    ]
