# Generated by Django 5.0.12 on 2025-04-28 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("patient_form", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SkinImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="skin_images/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="patient_form.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Diagnosis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("diagnosis_1", models.CharField(max_length=100)),
                ("confidence_1", models.FloatField()),
                ("diagnosis_2", models.CharField(max_length=100)),
                ("confidence_2", models.FloatField()),
                ("diagnosis_3", models.CharField(max_length=100)),
                ("confidence_3", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diagnoses",
                        to="diagnosis.skinimage",
                    ),
                ),
            ],
        ),
    ]
